/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ptc_2013;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.*;
import javax.swing.table.*;
import java.awt.*;
import java.awt.event.KeyEvent;
import java.net.URLDecoder;
import java.sql.*;
import java.util.Calendar;
import java.util.HashMap;
import java.util.Map;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;
/**
 *
 * @author David
 */
public class FrmFactura extends javax.swing.JFrame {

    /**
     * Creates new form FrmFactura
     */
    
    
    public void guardarFactura(){
        MtoFactura obj = new MtoFactura();
        Lista item1 = (Lista)cmbEmple.getSelectedItem();
        String codigo12 = String.valueOf(item1.getValue());
        
        
    obj.setFecha(txtFecha.getText());
    obj.setDUI_empleado(codigo12);
    
    obj.setTotal(Double.parseDouble(txt_total.getText()));
    if (obj.insertar_Factura()) {
      
    }
    else{
        
    }
    }
    public void guardarDetalle(){
        
        
        int numero;
        numero = tbDatos.getRowCount();
        
         
        //System.out.println(numero);
        for (int i = 0; i <numero; i++) {
            MtoFactura obj = new MtoFactura();
            obj.setCodigo_factura(Integer.parseInt(txtCod.getText()));
            
            obj.setCodigo_producto((Integer)tbDatos.getValueAt(i, 0));
           
            obj.setPrecio(Double.parseDouble(tbDatos.getValueAt(i, 2).toString()));
                  
            if (obj.insertar_Detale()) {
//                JOptionPane.showMessageDialog(this, null);
            }
            else{
//                JOptionPane.showMessageDialog(this, null);
            }
        }
    }
    
    
    public void verdaderaImpresion(){
        String path="";
        try {
            //String codigoParametro = "4";
            //Sacar la ubicacion path
            path = getClass().getResource("/Reportes/FrmFactura.jasper").getPath();
            //Decodificar
            path = URLDecoder.decode(path, "UTF-8");
            //Llamar la conexion
            Connection cn = new Conexion().conectar();
            //Crear parametros
            Map parametros = new HashMap();
            //parametros.put("",codigoParametro );
            parametros.put("cod_factura",Integer.parseInt(txtCod.getText()));
            //Crear el reporte
            JasperReport reporte = (JasperReport)JRLoader.loadObject(path);
            //Imprimir el reporte
            JasperPrint imprimir = JasperFillManager.fillReport(reporte, parametros, cn);
            //Mostrar reporte
            JasperViewer visor = new JasperViewer(imprimir, false);
            //JasperPrintManager.printReport(imprimir, true);
            //System.out.println(codigoParametro);
            visor.setTitle("Reporte de Productos");
            visor.setVisible(true);
        } catch (Exception e) {
            System.out.println("eerroorr:" + e.getMessage());
        }
    

            
    }
    
    
//    
    int codigo1;
    public FrmFactura() {
        initComponents();
        
         
        frmdi fondo = new frmdi("/imagenes/factura.jpg",800, 600);
        this.pnlFondo.add(fondo);
        this.pnlFondo.repaint();//Refrescar
        Image icono;
        icono = new ImageIcon(getClass().getResource("/img/icono.png")).getImage();
        this.setIconImage(icono);
        centrar();
        
        cargarCodigo();
        llenarEmple();
        cargarfecha();
        
    }
     public void cargarCodigo(){
        MtoFactura obj = new MtoFactura();
        obj.codFact();
        codigo1 = obj.getCodigo_factura();
        txtCod.setText(String.valueOf(obj.getCodigo_factura()));
        
        System.out.println(codigo1);
       
        
    }
     
       public void llenarEmple()
    {
        MtoFactura obj = new MtoFactura();
        
        obj.setModelo((DefaultComboBoxModel)cmbEmple.getModel());
        if(obj.cargarDatosEmpleado())
        {
            cmbEmple.setModel(obj.getModelo());
        }
    
    }
    
       public void cargarfecha()
    {
        Calendar c=Calendar.getInstance();
        this.txtFecha.setText(String.valueOf(c.get(Calendar.MONTH)+1)+ "/"+String.valueOf(c.get(Calendar.DAY_OF_MONTH))+"/"+String.valueOf(c.get(Calendar.YEAR)));
    }
    
    
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        pnlFondo = new javax.swing.JPanel();
        txt_total = new javax.swing.JTextField();
        lbl_total = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbDatos = new javax.swing.JTable();
        txt_codigoproducto = new javax.swing.JTextField();
        lbl_codigopr = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtCod = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cmbEmple = new javax.swing.JComboBox();
        jButton3 = new javax.swing.JButton();

        jFormattedTextField1.setText("jFormattedTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Facturación de productos");

        txt_total.setEditable(false);
        txt_total.setText("$0.00");
        txt_total.setToolTipText("");

        lbl_total.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_total.setText("Total:");

        tbDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Producto", "Tipo", "Precio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbDatos.setFocusable(false);
        jScrollPane1.setViewportView(tbDatos);

        txt_codigoproducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_codigoproductoKeyPressed(evt);
            }
        });

        lbl_codigopr.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_codigopr.setText("Producto:");

        jButton2.setText("FACTURAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("N° Factura");

        txtCod.setEnabled(false);
        txtCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Fecha:");

        txtFecha.setEnabled(false);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Empleado:");

        jButton3.setText("ELIMINAR PRODUCTO");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlFondoLayout = new javax.swing.GroupLayout(pnlFondo);
        pnlFondo.setLayout(pnlFondoLayout);
        pnlFondoLayout.setHorizontalGroup(
            pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlFondoLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFondoLayout.createSequentialGroup()
                        .addComponent(lbl_codigopr)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_codigoproducto, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlFondoLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtCod, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFondoLayout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(jLabel2)
                        .addGap(43, 43, 43)
                        .addComponent(txtFecha))
                    .addGroup(pnlFondoLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(cmbEmple, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(24, 24, 24))
            .addGroup(pnlFondoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlFondoLayout.createSequentialGroup()
                .addContainerGap(135, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(85, 85, 85)
                .addComponent(jButton3)
                .addGap(79, 79, 79)
                .addComponent(lbl_total)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_total, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        pnlFondoLayout.setVerticalGroup(
            pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFondoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_codigopr)
                    .addComponent(txt_codigoproducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(cmbEmple, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbl_total))
                    .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton2)
                        .addComponent(jButton3)))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    int filas = 0;
    double total = 0;
    private void txt_codigoproductoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_codigoproductoKeyPressed
        int tecla_presionada = evt.getKeyCode();
        
        if(tecla_presionada == KeyEvent.VK_ENTER)
        {
            ptc_2013.MtoProductos obj = new ptc_2013.MtoProductos();
            obj.setCodigo_producto(Integer.parseInt(txt_codigoproducto.getText()));
            
            if(obj.ConsultarProductos())
            {
               DefaultTableModel modelo = (DefaultTableModel) tbDatos.getModel();
               modelo.addRow(new Object[filas]);

               tbDatos.setValueAt(obj.getCodigo_producto(), filas, 0);
               tbDatos.setValueAt(obj.getNombre_producto(), filas, 1);
               tbDatos.setValueAt(obj.getPrecio_producto(), filas, 2);
               total = total + obj.getPrecio_producto() ;
               txt_total.setText(String.valueOf(total));
               filas++; 
               txt_codigoproducto.setText("");
            }
            else
            {
                JOptionPane.showMessageDialog(this, "ERROR: No se encuentra el producto.");
                txt_codigoproducto.setText("");
            }
        }
        
    }//GEN-LAST:event_txt_codigoproductoKeyPressed

    private void centrar() {
        Dimension Pantalla = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension formulario = this.getSize();
        int X = (Pantalla.width - formulario.width) / 2;
        int Y = (Pantalla.height - formulario.height) / 2;
        this.setLocation(X, Y);
    }
    private void txtCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        guardarFactura();
        guardarDetalle();
        verdaderaImpresion();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel modelo = (DefaultTableModel) tbDatos.getModel();
        modelo.removeRow(tbDatos.getSelectedRow());
    }//GEN-LAST:event_jButton3ActionPerformed
 /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmFactura().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmbEmple;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_codigopr;
    private javax.swing.JLabel lbl_total;
    private javax.swing.JPanel pnlFondo;
    private javax.swing.JTable tbDatos;
    private javax.swing.JTextField txtCod;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txt_codigoproducto;
    private javax.swing.JTextField txt_total;
    // End of variables declaration//GEN-END:variables
}
