/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ptc_2013;

import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URLDecoder;
import java.sql.Connection;
import java.util.HashMap;
import java.util.Map;
import javax.swing.ImageIcon;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Molina
 */
public class FrmReportes extends javax.swing.JFrame {

    /**
     * Creates new form FrmReportes
     */
    public FrmReportes() {
        initComponents();
        setTitle("SubReportes");
        frmdi fondo = new frmdi("/imgr/fondoreport.png",600, 600);
        this.pf.add(fondo);
        this.pf.repaint();//Refrescar
        frmdi fondo2 = new frmdi("/imgr/inventario1.png",128, 128);
        this.p1.add(fondo2);
        this.p1.repaint();//Refrescar
        frmdi fondo3 = new frmdi("/imgr/visitas1.png",128, 128);
        this.p2.add(fondo3);
        this.p2.repaint();//Refrescar
        frmdi fondo4 = new frmdi("/imgr/empleados1.png",128, 128);
        this.p3.add(fondo4);
        this.p3.repaint();//Refrescar
        frmdi fondo5 = new frmdi("/imgr/plantas1.png",128, 128);
        this.p4.add(fondo5);
        this.p4.repaint();//Refrescar
        frmdi fondo6 = new frmdi("/imgr/mant1.png",128, 128);
        this.p5.add(fondo6);
        this.p5.repaint();//Refrescar
        frmdi fondo7 = new frmdi("/imgr/riego1.png",128, 128);
        this.p6.add(fondo7);
        this.p6.repaint();//Refrescar
        frmdi fondo8 = new frmdi("/imgr/afili1.png",128, 128);
        this.p7.add(fondo8);
        this.p7.repaint();//Refrescar
        frmdi fondo9 = new frmdi("/imgr/emple1.png",128, 128);
        this.p8.add(fondo9);
        this.p8.repaint();//Refrescar
        frmdi fondo10 = new frmdi("/imgr/plaj.png",128, 128);
        this.p9.add(fondo10);
        this.p9.repaint();//Refrescar
        Image icono;
        icono = new ImageIcon(getClass().getResource("/img/icono.png")).getImage();
        this.setIconImage(icono);
        centrar();
    }
    private void centrar() {
        Dimension Pantalla = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension formulario = this.getSize();
        int X = (Pantalla.width - formulario.width) / 2;
        int Y = (Pantalla.height - formulario.height) / 2;
        this.setLocation(X, Y);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pf = new javax.swing.JPanel();
        p1 = new javax.swing.JPanel();
        p2 = new javax.swing.JPanel();
        p3 = new javax.swing.JPanel();
        p4 = new javax.swing.JPanel();
        p5 = new javax.swing.JPanel();
        p6 = new javax.swing.JPanel();
        p7 = new javax.swing.JPanel();
        p8 = new javax.swing.JPanel();
        p9 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtDesde = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtHasta = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        p1.setBackground(new java.awt.Color(204, 153, 255));
        p1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout p1Layout = new javax.swing.GroupLayout(p1);
        p1.setLayout(p1Layout);
        p1Layout.setHorizontalGroup(
            p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 128, Short.MAX_VALUE)
        );
        p1Layout.setVerticalGroup(
            p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 128, Short.MAX_VALUE)
        );

        p2.setBackground(new java.awt.Color(153, 0, 0));
        p2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout p2Layout = new javax.swing.GroupLayout(p2);
        p2.setLayout(p2Layout);
        p2Layout.setHorizontalGroup(
            p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 128, Short.MAX_VALUE)
        );
        p2Layout.setVerticalGroup(
            p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 128, Short.MAX_VALUE)
        );

        p3.setBackground(new java.awt.Color(204, 255, 204));
        p3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout p3Layout = new javax.swing.GroupLayout(p3);
        p3.setLayout(p3Layout);
        p3Layout.setHorizontalGroup(
            p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 128, Short.MAX_VALUE)
        );
        p3Layout.setVerticalGroup(
            p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 128, Short.MAX_VALUE)
        );

        p4.setBackground(new java.awt.Color(51, 255, 204));
        p4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout p4Layout = new javax.swing.GroupLayout(p4);
        p4.setLayout(p4Layout);
        p4Layout.setHorizontalGroup(
            p4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 128, Short.MAX_VALUE)
        );
        p4Layout.setVerticalGroup(
            p4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 128, Short.MAX_VALUE)
        );

        p5.setBackground(new java.awt.Color(153, 153, 0));
        p5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout p5Layout = new javax.swing.GroupLayout(p5);
        p5.setLayout(p5Layout);
        p5Layout.setHorizontalGroup(
            p5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 128, Short.MAX_VALUE)
        );
        p5Layout.setVerticalGroup(
            p5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 128, Short.MAX_VALUE)
        );

        p6.setBackground(new java.awt.Color(153, 255, 51));
        p6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout p6Layout = new javax.swing.GroupLayout(p6);
        p6.setLayout(p6Layout);
        p6Layout.setHorizontalGroup(
            p6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 128, Short.MAX_VALUE)
        );
        p6Layout.setVerticalGroup(
            p6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 128, Short.MAX_VALUE)
        );

        p7.setBackground(new java.awt.Color(0, 102, 102));
        p7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p7MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout p7Layout = new javax.swing.GroupLayout(p7);
        p7.setLayout(p7Layout);
        p7Layout.setHorizontalGroup(
            p7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 128, Short.MAX_VALUE)
        );
        p7Layout.setVerticalGroup(
            p7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 128, Short.MAX_VALUE)
        );

        p8.setBackground(new java.awt.Color(153, 102, 0));
        p8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p8MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout p8Layout = new javax.swing.GroupLayout(p8);
        p8.setLayout(p8Layout);
        p8Layout.setHorizontalGroup(
            p8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 128, Short.MAX_VALUE)
        );
        p8Layout.setVerticalGroup(
            p8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 128, Short.MAX_VALUE)
        );

        p9.setBackground(new java.awt.Color(0, 51, 153));
        p9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p9MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout p9Layout = new javax.swing.GroupLayout(p9);
        p9.setLayout(p9Layout);
        p9Layout.setHorizontalGroup(
            p9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 128, Short.MAX_VALUE)
        );
        p9Layout.setVerticalGroup(
            p9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 128, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Desde:");

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Hasta:");

        jButton1.setText("Mimebros");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Detalle");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pfLayout = new javax.swing.GroupLayout(pf);
        pf.setLayout(pfLayout);
        pfLayout.setHorizontalGroup(
            pfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pfLayout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(pfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pfLayout.createSequentialGroup()
                        .addComponent(p1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(p2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(p3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pfLayout.createSequentialGroup()
                        .addComponent(p5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(p6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(p7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pfLayout.createSequentialGroup()
                        .addComponent(p9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(107, 107, 107)))
                .addGroup(pfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(p4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(p8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pfLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(pfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2)
                            .addComponent(jButton1))))
                .addContainerGap())
            .addGroup(pfLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtDesde, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtHasta, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        pfLayout.setVerticalGroup(
            pfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pfLayout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addGroup(pfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pfLayout.createSequentialGroup()
                        .addGroup(pfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(p1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(p2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(p3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pfLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(p7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pfLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(pfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(p6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(p5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(pfLayout.createSequentialGroup()
                        .addComponent(p4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(p8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(pfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pfLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(p9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pfLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtDesde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtHasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void p1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p1MouseClicked
      String path = ""; 
     try
     {
         path = getClass().getResource("/Reportes/RptProductos.jasper").getPath();
         path = URLDecoder.decode(path, "UTF-8");
         
         Connection cn = new Conexion().conectar();
         Map parametros = new HashMap();
         
       
         
         parametros.put("Desde","hasta");
        
     
         
         JasperReport reporte = (JasperReport)JRLoader.loadObject(path);
         JasperPrint imprimir = JasperFillManager.fillReport(reporte, parametros, cn);
          
         JasperViewer visor = new JasperViewer(imprimir,false);
         visor.setTitle("Reporte de Productos");
         visor.setVisible(true);
            
     }
     catch (Exception ex)
     {
         System.out.println(ex.getMessage());
     }
                                              
    }//GEN-LAST:event_p1MouseClicked

    private void p2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p2MouseClicked
        String path = ""; 
     try
     {
         path = getClass().getResource("/Reportes/RptVisitas_Miembros.jasper").getPath();
         path = URLDecoder.decode(path, "UTF-8");
         
         Connection cn = new Conexion().conectar();
         Map parametros = new HashMap();
         
       
         
         parametros.put("Desde", txtDesde.getText());
         parametros.put("Hasta", txtHasta.getText());
     
         
         JasperReport reporte = (JasperReport)JRLoader.loadObject(path);
         JasperPrint imprimir = JasperFillManager.fillReport(reporte, parametros, cn);
          
         JasperViewer visor = new JasperViewer(imprimir,false);
         visor.setTitle("Reporte de Usuarios");
         visor.setVisible(true);
            
     }
     catch (Exception ex)
     {
         System.out.println(ex.getMessage());
     }
                     
    }//GEN-LAST:event_p2MouseClicked

    private void p3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p3MouseClicked
        String path = ""; 
     try
     {
         path = getClass().getResource("/Reportes/Mante_Zona_Empleados.jasper").getPath();
         path = URLDecoder.decode(path, "UTF-8");
         
         Connection cn = new Conexion().conectar();
         Map parametros = new HashMap();
         
       
         
         parametros.put("Desde", txtDesde.getText());
         parametros.put("Hasta", txtHasta.getText());
     
         
         JasperReport reporte = (JasperReport)JRLoader.loadObject(path);
         JasperPrint imprimir = JasperFillManager.fillReport(reporte, parametros, cn);
          
         JasperViewer visor = new JasperViewer(imprimir,false);
         visor.setTitle("Reporte de Empleados");
         visor.setVisible(true);
            
     }
     catch (Exception ex)
     {
         System.out.println(ex.getMessage());
     }
                     
    }//GEN-LAST:event_p3MouseClicked

    private void p4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p4MouseClicked
        // TODO add your handling code here:
         String path = ""; 
     try
     {
         path = getClass().getResource("/Reportes/RptZona_plantas.jasper").getPath();
         path = URLDecoder.decode(path, "UTF-8");
         
         Connection cn = new Conexion().conectar();
         Map parametros = new HashMap();
         
       
         
    
         
         JasperReport reporte = (JasperReport)JRLoader.loadObject(path);
         JasperPrint imprimir = JasperFillManager.fillReport(reporte, parametros, cn);
          
         JasperViewer visor = new JasperViewer(imprimir,false);
         visor.setTitle("Reporte de Zonas plantas");
         visor.setVisible(true);
            
     }
     catch (Exception ex)
     {
         System.out.println(ex.getMessage());
     }
                     
    }//GEN-LAST:event_p4MouseClicked

    private void p5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p5MouseClicked
        // TODO add your handling code here:
         String path = ""; 
     try
     {
         path = getClass().getResource("/Reportes/RptMante_Zonas_Emple.jasper").getPath();
         path = URLDecoder.decode(path, "UTF-8");
         
         Connection cn = new Conexion().conectar();
         Map parametros = new HashMap();
         
       
         
         parametros.put("Desde", txtDesde.getText());
         parametros.put("Hasta", txtHasta.getText());
     
         
         JasperReport reporte = (JasperReport)JRLoader.loadObject(path);
         JasperPrint imprimir = JasperFillManager.fillReport(reporte, parametros, cn);
          
         JasperViewer visor = new JasperViewer(imprimir,false);
         visor.setTitle("Reporte de Usuarios");
         visor.setVisible(true);
            
     }
     catch (Exception ex)
     {
         System.out.println(ex.getMessage());
     }
                     
    }//GEN-LAST:event_p5MouseClicked

    private void p6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p6MouseClicked
        // TODO add your handling code here:
         String path = ""; 
     try
     {
         path = getClass().getResource("/Reportes/RptRiego.jasper").getPath();
         path = URLDecoder.decode(path, "UTF-8");
         
         Connection cn = new Conexion().conectar();
         Map parametros = new HashMap();
         
       
         
         parametros.put("Desde", txtDesde.getText());
         parametros.put("Hasta", txtHasta.getText());
     
         
         JasperReport reporte = (JasperReport)JRLoader.loadObject(path);
         JasperPrint imprimir = JasperFillManager.fillReport(reporte, parametros, cn);
          
         JasperViewer visor = new JasperViewer(imprimir,false);
         visor.setTitle("Reporte de Usuarios");
         visor.setVisible(true);
            
     }
     catch (Exception ex)
     {
         System.out.println(ex.getMessage());
     }
                     
    }//GEN-LAST:event_p6MouseClicked

    private void p7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p7MouseClicked
        // TODO add your handling code here:
         String path = ""; 
     try
     {
         path = getClass().getResource("/Reportes/RptAfiliados.jasper").getPath();
         path = URLDecoder.decode(path, "UTF-8");
         
         Connection cn = new Conexion().conectar();
         Map parametros = new HashMap();
         
       
         
         parametros.put("Desde", txtDesde.getText());
         parametros.put("Hasta", txtHasta.getText());
     
         
         JasperReport reporte = (JasperReport)JRLoader.loadObject(path);
         JasperPrint imprimir = JasperFillManager.fillReport(reporte, parametros, cn);
          
         JasperViewer visor = new JasperViewer(imprimir,false);
         visor.setTitle("Reporte de Usuarios");
         visor.setVisible(true);
            
     }
     catch (Exception ex)
     {
         System.out.println(ex.getMessage());
     }
                     
    }//GEN-LAST:event_p7MouseClicked

    private void p8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p8MouseClicked
        // TODO add your handling code here:
         String path = ""; 
     try
     {
         path = getClass().getResource("/Reportes/RptMante_Zona_Emple.jasper").getPath();
         path = URLDecoder.decode(path, "UTF-8");
         
         Connection cn = new Conexion().conectar();
         Map parametros = new HashMap();
         
       
         
         parametros.put("Desde", txtDesde.getText());
         parametros.put("Hasta", txtHasta.getText());
     
         
         JasperReport reporte = (JasperReport)JRLoader.loadObject(path);
         JasperPrint imprimir = JasperFillManager.fillReport(reporte, parametros, cn);
          
         JasperViewer visor = new JasperViewer(imprimir,false);
         visor.setTitle("Reporte de Usuarios");
         visor.setVisible(true);
            
     }
     catch (Exception ex)
     {
         System.out.println(ex.getMessage());
     }
                     
    }//GEN-LAST:event_p8MouseClicked

    private void p9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p9MouseClicked
        // TODO add your handling code here:
         String path = ""; 
     try
     {
         path = getClass().getResource("/Reportes/RptPlantas.jasper").getPath();
         path = URLDecoder.decode(path, "UTF-8");
         
         Connection cn = new Conexion().conectar();
         Map parametros = new HashMap();
         
       
         
         parametros.put("Desde", txtDesde.getText());
         parametros.put("Hasta", txtHasta.getText());
     
         
         JasperReport reporte = (JasperReport)JRLoader.loadObject(path);
         JasperPrint imprimir = JasperFillManager.fillReport(reporte, parametros, cn);
          
         JasperViewer visor = new JasperViewer(imprimir,false);
         visor.setTitle("Reporte de Usuarios");
         visor.setVisible(true);
            
     }
     catch (Exception ex)
     {
         System.out.println(ex.getMessage());
     }
                     
    }//GEN-LAST:event_p9MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         String path = ""; 
     try
     {
         path = getClass().getResource("/Reportes/RptVisitas_Miembros.jasper").getPath();
         path = URLDecoder.decode(path, "UTF-8");
         
         Connection cn = new Conexion().conectar();
         Map parametros = new HashMap();
         
       
         
         parametros.put("Desde", txtDesde.getText());
         parametros.put("Hasta", txtHasta.getText());
     
         
         JasperReport reporte = (JasperReport)JRLoader.loadObject(path);
         JasperPrint imprimir = JasperFillManager.fillReport(reporte, parametros, cn);
          
         JasperViewer visor = new JasperViewer(imprimir,false);
         visor.setTitle("Reporte de Usuarios");
         visor.setVisible(true);
            
     }
     catch (Exception ex)
     {
         System.out.println(ex.getMessage());
     }
                     
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String path = ""; 
     try
     {
         path = getClass().getResource("/Reportes/RptDetalle.jasper").getPath();
         path = URLDecoder.decode(path, "UTF-8");
         
         Connection cn = new Conexion().conectar();
         Map parametros = new HashMap();
         
       
         
       
         
         JasperReport reporte = (JasperReport)JRLoader.loadObject(path);
         JasperPrint imprimir = JasperFillManager.fillReport(reporte, parametros, cn);
          
         JasperViewer visor = new JasperViewer(imprimir,false);
         visor.setTitle("Reporte de Detalle");
         visor.setVisible(true);
            
     }
     catch (Exception ex)
     {
         System.out.println(ex.getMessage());
     }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmReportes().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel p1;
    private javax.swing.JPanel p2;
    private javax.swing.JPanel p3;
    private javax.swing.JPanel p4;
    private javax.swing.JPanel p5;
    private javax.swing.JPanel p6;
    private javax.swing.JPanel p7;
    private javax.swing.JPanel p8;
    private javax.swing.JPanel p9;
    private javax.swing.JPanel pf;
    private javax.swing.JTextField txtDesde;
    private javax.swing.JTextField txtHasta;
    // End of variables declaration//GEN-END:variables
}
