/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ptc_2013;

import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.net.URLDecoder;
import java.sql.Connection;
import java.util.HashMap;
import java.util.Map;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author David
 */
public class FrmSocio extends javax.swing.JFrame {

    /**
     * Creates new form FrmSocio
     */
    public FrmSocio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnlFondo = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txtDirSocio2 = new javax.swing.JTextField();
        lblDireccion_socio2 = new javax.swing.JLabel();
        txtProfesionSocio2 = new javax.swing.JTextField();
        cbEstado_civil = new javax.swing.JComboBox();
        lblEstadocivil2 = new javax.swing.JLabel();
        lblProfesion2 = new javax.swing.JLabel();
        lblNum_membresia2 = new javax.swing.JLabel();
        txtNum_membresía2 = new javax.swing.JTextField();
        txtFechaInicio = new javax.swing.JFormattedTextField();
        lblFecha_inicio2 = new javax.swing.JLabel();
        lblFecha_fin2 = new javax.swing.JLabel();
        txtFechaFin = new javax.swing.JFormattedTextField();
        lblEmail_socio2 = new javax.swing.JLabel();
        txtEmail2 = new javax.swing.JTextField();
        lblTelefono_socio2 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JFormattedTextField();
        lblApellido_socio2 = new javax.swing.JLabel();
        txtApellidoSocio2 = new javax.swing.JTextField();
        lblNombre_socio2 = new javax.swing.JLabel();
        txtNombreSocio2 = new javax.swing.JTextField();
        lblITM2 = new javax.swing.JLabel();
        cbnITM2 = new javax.swing.JComboBox();
        lblDui_socio2 = new javax.swing.JLabel();
        txtDui = new javax.swing.JFormattedTextField();
        btnAgregar3 = new javax.swing.JButton();
        btnModificar3 = new javax.swing.JButton();
        btnEliminar3 = new javax.swing.JButton();
        txtBuscar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbAfiliados = new javax.swing.JTable();
        btnConsultar = new javax.swing.JButton();
        btnLimpiar1 = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Afiliados del jardín");
        setResizable(false);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Registros"));

        txtDirSocio2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDirSocio2KeyTyped(evt);
            }
        });

        lblDireccion_socio2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblDireccion_socio2.setForeground(new java.awt.Color(255, 255, 255));
        lblDireccion_socio2.setText("Dirección del Socio:");

        txtProfesionSocio2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtProfesionSocio2KeyTyped(evt);
            }
        });

        cbEstado_civil.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Soltero", "Casado", "Viudo", "Acompañado" }));
        cbEstado_civil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbEstado_civilActionPerformed(evt);
            }
        });

        lblEstadocivil2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblEstadocivil2.setForeground(new java.awt.Color(255, 255, 255));
        lblEstadocivil2.setText("Estado Civil:");

        lblProfesion2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblProfesion2.setForeground(new java.awt.Color(255, 255, 255));
        lblProfesion2.setText("Profesión:");

        lblNum_membresia2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblNum_membresia2.setForeground(new java.awt.Color(255, 255, 255));
        lblNum_membresia2.setText("Número de membresía:");

        txtNum_membresía2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNum_membresía2KeyTyped(evt);
            }
        });

        try {
            txtFechaInicio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtFechaInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaInicioActionPerformed(evt);
            }
        });
        txtFechaInicio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFechaInicioKeyTyped(evt);
            }
        });

        lblFecha_inicio2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblFecha_inicio2.setForeground(new java.awt.Color(255, 255, 255));
        lblFecha_inicio2.setText("Fecha de inicio:");

        lblFecha_fin2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblFecha_fin2.setForeground(new java.awt.Color(255, 255, 255));
        lblFecha_fin2.setText("Fecha de fin:");

        try {
            txtFechaFin.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        lblEmail_socio2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblEmail_socio2.setForeground(new java.awt.Color(255, 255, 255));
        lblEmail_socio2.setText("Email del socio:");

        lblTelefono_socio2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblTelefono_socio2.setForeground(new java.awt.Color(255, 255, 255));
        lblTelefono_socio2.setText("Telefono del Socio:");

        try {
            txtTelefono.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyTyped(evt);
            }
        });

        lblApellido_socio2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblApellido_socio2.setForeground(new java.awt.Color(255, 255, 255));
        lblApellido_socio2.setText("Apellido del Socio:");

        txtApellidoSocio2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellidoSocio2KeyTyped(evt);
            }
        });

        lblNombre_socio2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblNombre_socio2.setForeground(new java.awt.Color(255, 255, 255));
        lblNombre_socio2.setText("Nombre del Socio:");

        txtNombreSocio2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreSocio2KeyTyped(evt);
            }
        });

        lblITM2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblITM2.setForeground(new java.awt.Color(255, 255, 255));
        lblITM2.setText(" Tipo de membresía:");

        lblDui_socio2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblDui_socio2.setForeground(new java.awt.Color(255, 255, 255));
        lblDui_socio2.setText("Dui del socio:");

        try {
            txtDui.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#######-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDui.setToolTipText("");
        txtDui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDuiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblNombre_socio2)
                                .addComponent(lblApellido_socio2))
                            .addComponent(lblEmail_socio2)
                            .addComponent(lblTelefono_socio2))
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(lblITM2)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(lblDui_socio2)
                        .addGap(54, 54, 54)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(cbnITM2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtApellidoSocio2)
                        .addComponent(txtNombreSocio2, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtEmail2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDui, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNum_membresia2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDireccion_socio2)
                            .addComponent(lblProfesion2)
                            .addComponent(lblEstadocivil2)
                            .addComponent(lblFecha_fin2)
                            .addComponent(lblFecha_inicio2))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtNum_membresía2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtProfesionSocio2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtDirSocio2, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(cbEstado_civil, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtFechaFin, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtFechaInicio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblDireccion_socio2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtDirSocio2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDui_socio2)
                            .addComponent(txtDui, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblITM2)
                    .addComponent(cbnITM2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblProfesion2)
                    .addComponent(txtProfesionSocio2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreSocio2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombre_socio2)
                    .addComponent(lblEstadocivil2)
                    .addComponent(cbEstado_civil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtApellidoSocio2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblApellido_socio2)
                    .addComponent(lblNum_membresia2)
                    .addComponent(txtNum_membresía2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(lblTelefono_socio2))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEmail_socio2)
                            .addComponent(txtEmail2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(lblFecha_inicio2))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(txtFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFecha_fin2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 11, Short.MAX_VALUE)))))
                .addGap(54, 54, 54))
        );

        btnAgregar3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add.png"))); // NOI18N
        btnAgregar3.setText("Agregar");
        btnAgregar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregar3ActionPerformed(evt);
            }
        });

        btnModificar3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/refresh.png"))); // NOI18N
        btnModificar3.setText("Modificar");
        btnModificar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificar3ActionPerformed(evt);
            }
        });

        btnEliminar3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/delete.png"))); // NOI18N
        btnEliminar3.setText("Eliminar");
        btnEliminar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminar3ActionPerformed(evt);
            }
        });

        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBuscarKeyTyped(evt);
            }
        });

        tbAfiliados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Dui ", "Tipo", "Nombre", "Apellido", "Telefono", "Email", "Direccion", "Profesion", "Estado civil", "Numero membresia", "Fecha inicio", "Fecha fin"
            }
        ));
        tbAfiliados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbAfiliadosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbAfiliados);

        btnConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search.png"))); // NOI18N
        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        btnLimpiar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/promotion.png"))); // NOI18N
        btnLimpiar1.setText("Limpiar");
        btnLimpiar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlFondoLayout = new javax.swing.GroupLayout(pnlFondo);
        pnlFondo.setLayout(pnlFondoLayout);
        pnlFondoLayout.setHorizontalGroup(
            pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFondoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFondoLayout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnModificar3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                            .addComponent(btnAgregar3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEliminar3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFondoLayout.createSequentialGroup()
                        .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlFondoLayout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnConsultar)
                                .addGap(47, 47, 47)
                                .addComponent(btnLimpiar1)))
                        .addGap(195, 195, 195))))
        );
        pnlFondoLayout.setVerticalGroup(
            pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFondoLayout.createSequentialGroup()
                .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFondoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlFondoLayout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(btnAgregar3)
                        .addGap(27, 27, 27)
                        .addComponent(btnModificar3)
                        .addGap(42, 42, 42)
                        .addComponent(btnEliminar3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConsultar)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpiar1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFondo, javax.swing.GroupLayout.PREFERRED_SIZE, 865, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDirSocio2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDirSocio2KeyTyped
        // TODO add your handling code here:
     
    }//GEN-LAST:event_txtDirSocio2KeyTyped

    private void txtProfesionSocio2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtProfesionSocio2KeyTyped
        // TODO add your handling code here:
      
    }//GEN-LAST:event_txtProfesionSocio2KeyTyped

    private void cbEstado_civilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbEstado_civilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbEstado_civilActionPerformed

    private void txtNum_membresía2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNum_membresía2KeyTyped
        // TODO add your handling code here:
      
    }//GEN-LAST:event_txtNum_membresía2KeyTyped

    private void txtFechaInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaInicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaInicioActionPerformed

    private void txtFechaInicioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFechaInicioKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaInicioKeyTyped

    private void txtTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if ((c < '0' || c > '9')) {
            evt.consume();
        }
    }//GEN-LAST:event_txtTelefonoKeyTyped

    private void txtApellidoSocio2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoSocio2KeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if ((c < 'a' || c > 'z') && (c < 'A' || c > 'Z') && (c != (char) KeyEvent.VK_SPACE)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtApellidoSocio2KeyTyped

    private void txtNombreSocio2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreSocio2KeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if ((c < 'a' || c > 'z') && (c < 'A' || c > 'Z')
            && (c != (char) KeyEvent.VK_SPACE)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtNombreSocio2KeyTyped

    private void txtDuiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDuiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDuiActionPerformed

    private void btnAgregar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregar3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregar3ActionPerformed

    private void btnModificar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificar3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModificar3ActionPerformed

    private void btnEliminar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminar3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminar3ActionPerformed

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
        // TODO add your handling code here:
        MtoAfiliado obj = new MtoAfiliado();

        obj.setFiltro(txtBuscar.getText());
        obj.setModelo((DefaultTableModel) tbAfiliados.getModel());
        if (obj.consultarTabla()) {
            tbAfiliados.setModel(obj.getModelo());
        }
        char c = evt.getKeyChar();
        if ((c < 'a' || c > 'z') && (c < 'A' || c > 'Z')) {
            evt.consume();
        }
    }//GEN-LAST:event_txtBuscarKeyReleased

    private void txtBuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if ((c < 'a' || c > 'z') && (c < 'A' || c > 'Z')) {
            evt.consume();
        }
    }//GEN-LAST:event_txtBuscarKeyTyped

    private void tbAfiliadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbAfiliadosMouseClicked
        // TODO add your handling code here:
//        int fila = tbAfiliados.getSelectedRow();
//        limpiarCampos();
//        btnAgregar2.setEnabled(false);
//        btnModificar2.setEnabled(true);
//        btnEliminar2.setEnabled(true);
//        //Datos
//
//        String dui = (String) tbAfiliados.getValueAt(fila,0);
//
//        String nombre = (String) tbAfiliados.getValueAt(fila,2);
//        String apellido  = (String) tbAfiliados.getValueAt(fila,3);
//        String telefono = (String) tbAfiliados.getValueAt(fila,4);
//        String email = (String) tbAfiliados.getValueAt(fila,5);
//        String direccion = (String) tbAfiliados.getValueAt(fila,6);
//        String profesion = (String) tbAfiliados.getValueAt(fila,7);
//        String estado_civil = (String) tbAfiliados.getValueAt(fila,8);
//        String Num  = (String) tbAfiliados.getValueAt(fila,9);
//        String fecha_i = (String) tbAfiliados.getValueAt(fila,10);
//        String fecha_f = (String) tbAfiliados.getValueAt(fila,11);
//
//        txtDui.setText(dui);
//        txtApellidoSocio2.setText(apellido);
//        txtNombreSocio2.setText(nombre);
//        txtTelefono.setText(telefono);
//        txtDirSocio2.setText(direccion);
//        txtEmail2.setText(email);
//        txtProfesionSocio2.setText(profesion);
//        txtNum_membresía2.setText(Num);
//        txtFechaInicio.setText(fecha_i);
//        txtFechaFin.setText(fecha_f);
    }//GEN-LAST:event_tbAfiliadosMouseClicked

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        // TODO add your handling code here:

        MtoAfiliado obj = new MtoAfiliado();
        obj.setModelo((DefaultTableModel) tbAfiliados.getModel());
        if (obj.ConsultarAfiliados()) {
            tbAfiliados.setModel(obj.getModelo());
        }
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnLimpiar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiar1ActionPerformed
        // TODO add your handling code here:
//
//        limpiarCampos();
//        cargarCodigo();
//
//        btnagregar.setEnabled(true);
//
//        btnmodi.setEnabled(false);
//        btneliminar.setEnabled(false);
//
//        DefaultTableModel model = (DefaultTableModel)tbDatos.getModel() ;
//        model.setRowCount(0) ;
    }//GEN-LAST:event_btnLimpiar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmSocio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmSocio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmSocio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmSocio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmSocio().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar3;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnEliminar3;
    private javax.swing.JButton btnLimpiar1;
    private javax.swing.JButton btnModificar3;
    private javax.swing.JComboBox cbEstado_civil;
    private javax.swing.JComboBox cbnITM2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblApellido_socio2;
    private javax.swing.JLabel lblDireccion_socio2;
    private javax.swing.JLabel lblDui_socio2;
    private javax.swing.JLabel lblEmail_socio2;
    private javax.swing.JLabel lblEstadocivil2;
    private javax.swing.JLabel lblFecha_fin2;
    private javax.swing.JLabel lblFecha_inicio2;
    private javax.swing.JLabel lblITM2;
    private javax.swing.JLabel lblNombre_socio2;
    private javax.swing.JLabel lblNum_membresia2;
    private javax.swing.JLabel lblProfesion2;
    private javax.swing.JLabel lblTelefono_socio2;
    private javax.swing.JPanel pnlFondo;
    private javax.swing.JTable tbAfiliados;
    private javax.swing.JTextField txtApellidoSocio2;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtDirSocio2;
    private javax.swing.JFormattedTextField txtDui;
    private javax.swing.JTextField txtEmail2;
    private javax.swing.JFormattedTextField txtFechaFin;
    private javax.swing.JFormattedTextField txtFechaInicio;
    private javax.swing.JTextField txtNombreSocio2;
    private javax.swing.JTextField txtNum_membresía2;
    private javax.swing.JTextField txtProfesionSocio2;
    private javax.swing.JFormattedTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
