/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ptc_2013;

import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URLDecoder;
import java.sql.Connection;
import java.util.HashMap;
import java.util.Map;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Carlos_Cornejo
 */
public class FrmTipo_Producto extends javax.swing.JFrame {

    /**
     * Creates new form FrmTipo_Producto
     */
    int codi_tipo;
    public FrmTipo_Producto() {
        
        initComponents();
        cargarCodigo();
        centrar();
        frmdi fondo = new frmdi("/imagenes/jardin.png", 590,700);
         this.pnlFondo.add(fondo);
         this.pnlFondo.repaint();// repintar o refrescar
             Image icono;
        icono = new ImageIcon(getClass().getResource("/img/plantas.png")).getImage();
        this.setIconImage(icono);
    }
     public void limpiarCampos()
{
             txtNomProd.setText("");
             txtDetalle.setText("");
             
             
}
     private void centrar(){
       Dimension Pantalla = Toolkit.getDefaultToolkit().getScreenSize();
       Dimension formulario = this.getSize();
       int X = (Pantalla.width- formulario.width)/2;
       int Y =(Pantalla.height- formulario.height)/2;
       this.setLocation(X,Y);
       }
              
       public void cargarCodigo(){
          
MtoTipo_Producto obj = new MtoTipo_Producto();
obj.codTipoProducto();
codi_tipo= obj.getId_tipo_producto();
txtITP.setText(String.valueOf(obj.getId_tipo_producto()));
System.out.println(codi_tipo);

}    
//        public void inicio(){
//              btnEliminar.setEnabled(false);
//              btnModificar.setEnabled(false);
//             
//              
//              }
//                public void btnElim(){
//              btnAgregar.setEnabled(false);
//              btnModificar.setEnabled(false);
//             
//              
//              }
//                public void btnCons(){
//              btnAgregar.setEnabled(false);
//              
//              }
//                  public void btnLimp(){
//              btnAgregar.setEnabled(true);
//              
//              }
                

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFondo = new javax.swing.JPanel();
        pnlTP = new javax.swing.JPanel();
        lblIdTP = new javax.swing.JLabel();
        lblNomProd = new javax.swing.JLabel();
        lblDTP = new javax.swing.JLabel();
        txtITP = new javax.swing.JTextField();
        txtNomProd = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDetalle = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbTipo_Productos = new javax.swing.JTable();
        btnAgregar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        txtBuscar = new javax.swing.JTextField();
        btnLimpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tipo de Productos");

        pnlTP.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        pnlTP.setOpaque(false);

        lblIdTP.setForeground(new java.awt.Color(255, 255, 204));
        lblIdTP.setText("Código:");

        lblNomProd.setForeground(new java.awt.Color(255, 255, 204));
        lblNomProd.setText("Nombre:");

        lblDTP.setForeground(new java.awt.Color(255, 255, 204));
        lblDTP.setText("Detalle:");

        txtITP.setEditable(false);
        txtITP.setEnabled(false);

        txtNomProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomProdActionPerformed(evt);
            }
        });
        txtNomProd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNomProdKeyTyped(evt);
            }
        });

        txtDetalle.setColumns(20);
        txtDetalle.setRows(5);
        txtDetalle.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDetalleKeyTyped(evt);
            }
        });
        jScrollPane2.setViewportView(txtDetalle);

        javax.swing.GroupLayout pnlTPLayout = new javax.swing.GroupLayout(pnlTP);
        pnlTP.setLayout(pnlTPLayout);
        pnlTPLayout.setHorizontalGroup(
            pnlTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTPLayout.createSequentialGroup()
                .addGroup(pnlTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNomProd)
                    .addComponent(lblIdTP)
                    .addGroup(pnlTPLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblDTP)))
                .addGap(19, 19, 19)
                .addGroup(pnlTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtNomProd, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlTPLayout.createSequentialGroup()
                        .addGroup(pnlTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlTPLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtITP, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(62, 62, 62))
        );
        pnlTPLayout.setVerticalGroup(
            pnlTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTPLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(pnlTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdTP)
                    .addComponent(txtITP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomProd)
                    .addComponent(txtNomProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlTPLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(lblDTP))))
        );

        tbTipo_Productos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "tipo de producto", "nombre de producto", "detalle"
            }
        ));
        tbTipo_Productos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbTipo_ProductosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbTipo_Productos);

        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add.png"))); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/refresh.png"))); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/delete.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search.png"))); // NOI18N
        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/reporte.png"))); // NOI18N
        jButton1.setText("Reportes");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBuscarKeyTyped(evt);
            }
        });

        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/process.png"))); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlFondoLayout = new javax.swing.GroupLayout(pnlFondo);
        pnlFondo.setLayout(pnlFondoLayout);
        pnlFondoLayout.setHorizontalGroup(
            pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFondoLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlFondoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(pnlFondoLayout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnConsultar)
                        .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlFondoLayout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jButton1))
                            .addGroup(pnlFondoLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnLimpiar))))
                    .addGroup(pnlFondoLayout.createSequentialGroup()
                        .addComponent(pnlTP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnModificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(0, 28, Short.MAX_VALUE))
        );
        pnlFondoLayout.setVerticalGroup(
            pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFondoLayout.createSequentialGroup()
                .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFondoLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(btnAgregar)
                        .addGap(17, 17, 17)
                        .addComponent(btnModificar)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlFondoLayout.createSequentialGroup()
                        .addContainerGap(29, Short.MAX_VALUE)
                        .addComponent(pnlTP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnConsultar)
                            .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLimpiar))
                        .addGap(5, 5, 5)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pnlTP.getAccessibleContext().setAccessibleName("Datos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomProdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomProdActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
         MtoTipo_Producto obj = new MtoTipo_Producto();
//         inicio ();
        obj.setNombre_producto(String.valueOf(txtNomProd.getText()));
        obj.setDetalle_tipo_producto(String.valueOf(txtDetalle.getText()));
        if( obj.AgregarTipo_Productos())
        {
            JOptionPane.showMessageDialog(this, "Datos Agregados con éxito");
            limpiarCampos();
            cargarCodigo();
            
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Datos con error");
        }
         btnAgregar.setEnabled(true);
          btnModificar.setEnabled(false);
          btnEliminar.setEnabled(false);
        
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        MtoTipo_Producto obj = new MtoTipo_Producto();
        obj.setId_tipo_producto(Integer.parseInt(txtITP.getText()));
        obj.setNombre_producto(String.valueOf(txtNomProd.getText()));
        obj.setDetalle_tipo_producto(String.valueOf(txtDetalle.getText()));
         if(obj.modificarTipo_Producto())
        {
            JOptionPane.showMessageDialog(this, "Datos Modificados");
            limpiarCampos();
            cargarCodigo();
        }
        else
          {
             JOptionPane.showMessageDialog(this, "ERROR");
           }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        
        MtoTipo_Producto obj = new MtoTipo_Producto();
//        btnElim();
        obj.setId_tipo_producto(Integer.parseInt(txtITP.getText()));
        obj.setNombre_producto(String.valueOf(txtNomProd.getText()));
        obj.setDetalle_tipo_producto(String.valueOf(txtDetalle.getText()));
        int eliminar = JOptionPane.showConfirmDialog(this, "¿Está seguro que desea eliminar?",
             "Atención", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                       if(eliminar == 0)
                     {
                         if(obj.eliminarTipo_Producto())
                        {
                           JOptionPane.showMessageDialog(this, "Datos Eliminados");
                           limpiarCampos();
                           cargarCodigo();
                        }
                        else
                       {
                           JOptionPane.showMessageDialog(this, "ERROR");
                        }
                     }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        // TODO add your handling code here:
         MtoTipo_Producto obj = new MtoTipo_Producto();
          obj.setModelo((DefaultTableModel)tbTipo_Productos.getModel());
        if(obj.ConsultarTipoProductos())
        {
            tbTipo_Productos.setModel(obj.getModelo());
        }
//        obj.setId_tipo_producto(Integer.parseInt(txtITP.getText()));
//        obj.setNombre_producto(String.valueOf(txtNomProd.getText()));
//        obj.setDetalle_tipo_producto(String.valueOf(txtDetalle.getText()));
//        if( obj.ConsultarTipoProductos())
//        { obj.setId_tipo_producto(Integer.parseInt(txtITP.getText()));
//    
//            
//        }
        
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
         DefaultTableModel model = (DefaultTableModel)tbTipo_Productos.getModel() ; 
        model.setRowCount(0) ;
//        btnLimp();
        
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void txtNomProdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomProdKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if((c< 'a' || c>'z') && (c<'A' || c>'Z')) evt.consume();
    }//GEN-LAST:event_txtNomProdKeyTyped

    private void txtDetalleKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDetalleKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if((c< 'a' || c>'z') && (c<'A' || c>'Z')) evt.consume();
    }//GEN-LAST:event_txtDetalleKeyTyped

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
        // TODO add your handling code here:
        MtoTipo_Producto obj = new MtoTipo_Producto();
         
        obj.setFiltro(txtBuscar.getText());
        obj.setModelo((DefaultTableModel)tbTipo_Productos.getModel());
        if(obj.consultarTabla())
        {
            tbTipo_Productos.setModel(obj.getModelo());
        }
         char c = evt.getKeyChar();
        if((c< 'a' || c>'z') && (c<'A' || c>'Z') ) evt.consume();
        else{ ;
        }
        
        
    }//GEN-LAST:event_txtBuscarKeyReleased

    private void txtBuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if((c< 'a' || c>'z') && (c<'A' || c>'Z')) evt.consume();
       
    }//GEN-LAST:event_txtBuscarKeyTyped

    private void tbTipo_ProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbTipo_ProductosMouseClicked
        // TODO add your handling code here:
        int fila = tbTipo_Productos.getSelectedRow();
          
          limpiarCampos();
          
          btnAgregar.setEnabled(false);
          btnModificar.setEnabled(true);
          btnEliminar.setEnabled(true);
          //Datos

          
        this.txtITP.setText(tbTipo_Productos.getValueAt(fila, 0).toString());  
        String nombre = (String) tbTipo_Productos.getValueAt(fila,1);
        String descripcion = (String) tbTipo_Productos.getValueAt(fila,2);
   

        txtNomProd.setText(nombre);
        txtDetalle.setText(descripcion);
       
    }//GEN-LAST:event_tbTipo_ProductosMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String path="";
        try {
            //String codigoParametro = "4";
            //Sacar la ubicacion path
            path = getClass().getResource("/Reportes/RptTipo_Producto.jasper").getPath();
            //Decodificar
            path = URLDecoder.decode(path, "UTF-8");
            //Llamar la conexion
            Connection cn = new Conexion().conectar();
            //Crear parametros
            Map parametros = new HashMap();
            //parametros.put("",codigoParametro );
            parametros.put("hola","mundo");
            //Crear el reporte
            JasperReport reporte = (JasperReport)JRLoader.loadObject(path);
            //Imprimir el reporte
            JasperPrint imprimir = JasperFillManager.fillReport(reporte, parametros, cn);
            //Mostrar reporte
            JasperViewer visor = new JasperViewer(imprimir, false);
            //System.out.println(codigoParametro);
            visor.setTitle("Reporte de Tipo Productos");
            visor.setVisible(true);
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmTipo_Producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmTipo_Producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmTipo_Producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmTipo_Producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmTipo_Producto().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblDTP;
    private javax.swing.JLabel lblIdTP;
    private javax.swing.JLabel lblNomProd;
    private javax.swing.JPanel pnlFondo;
    private javax.swing.JPanel pnlTP;
    private javax.swing.JTable tbTipo_Productos;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextArea txtDetalle;
    private javax.swing.JTextField txtITP;
    private javax.swing.JTextField txtNomProd;
    // End of variables declaration//GEN-END:variables
}
