/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ptc_2013;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URLDecoder;
import java.sql.Connection;
import java.util.Calendar;
import java.util.HashMap;
import java.util.Map;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;
/**
 *
 * @author Todos
 */
public class FrmVis extends javax.swing.JFrame {

    /**
     * Creates new form FrmVis
     */int visita;
     int tipoVisita=0;
    public FrmVis() {
        initComponents();
        
          frmdi fondo = new frmdi("/img/titi.jpg", 500,600);
         this.pf.add(fondo);
         this.pf.repaint();// repintar o refrescar
           Image icono;
        icono = new ImageIcon(getClass().getResource("/img/icono.png")).getImage();
        this.setIconImage(icono);
        cargarfecha();
        cargarCodigo();
        centrar();
//        llenarCombo();
    }
 public void cargarCodigo(){
MtoGrupo obj = new MtoGrupo();
obj.codvis();
visita = obj.getVisita();
txtid.setText(String.valueOf(obj.getVisita()));


}
//   public void llenarCombo()
//    {
//        MtoVis obj = new MtoVis();
//        obj.setModelo2((DefaultComboBoxModel)cbtipo.getModel());
//        if(obj.cargarDatosCombo())
//        {
//            cbtipo.setModel(obj.getModelo2());
//        }
//    
//    }
   public void limpiar()
   {
    
       tipoVisita=0;
       grupo.setSelected(false);
       solo.setSelected(false);
       txtmonto.setText("");
       txtCan.setText("");
       txtCan1.setText("");
       txtCan2.setText("");
      
   }
   
   public void centrar()
   {
     Dimension pantalla = Toolkit.getDefaultToolkit().getScreenSize();
     Dimension formulario = this.getSize();
     int X = (pantalla.width - formulario.width)/2;
     int Y = (pantalla.height - formulario.height)/2;
             this.setLocation(X, Y);
   }
    
    public void cargarfecha()
    {
        Calendar c=Calendar.getInstance();
        this.txtfecha.setText(String.valueOf(c.get(Calendar.MONTH)+1)+ "/"+String.valueOf(c.get(Calendar.DAY_OF_MONTH))+"/"+String.valueOf(c.get(Calendar.YEAR)));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        btneliminar = new javax.swing.JButton();
        pf = new javax.swing.JPanel();
        btnconsul3 = new javax.swing.JButton();
        btnmodi = new javax.swing.JButton();
        btnagregar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        txtfecha = new javax.swing.JTextField();
        btnLimpiar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tb = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        txtCan = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtCan1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtCan2 = new javax.swing.JTextField();
        solo = new javax.swing.JRadioButton();
        grupo = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtmonto = new javax.swing.JTextField();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        btneliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/delete.png"))); // NOI18N
        btneliminar.setText("Eliminar");
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Visitante");
        setResizable(false);

        btnconsul3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search.png"))); // NOI18N
        btnconsul3.setText("Consultar");
        btnconsul3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconsul3ActionPerformed(evt);
            }
        });

        btnmodi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/refresh.png"))); // NOI18N
        btnmodi.setText("Modificar");
        btnmodi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodiActionPerformed(evt);
            }
        });

        btnagregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add.png"))); // NOI18N
        btnagregar.setText("Agregar");
        btnagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagregarActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Numero de Visitante:");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Tipo de visitante:");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Ingreso:");

        txtid.setEnabled(false);

        txtfecha.setEnabled(false);

        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/promotion.png"))); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        tb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Número", "Monto", "Tipo", "Ingreso", "Cantidad", "Numero vis"
            }
        ));
        tb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tb);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Cantidad de niños :");

        txtCan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCanKeyReleased(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/refresh.png"))); // NOI18N
        jButton1.setText("Miembros");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Cantidad de adultos :");

        txtCan1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCan1KeyReleased(evt);
            }
        });

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Cantidad de ancianos:");

        txtCan2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCan2KeyReleased(evt);
            }
        });

        solo.setForeground(new java.awt.Color(255, 255, 255));
        solo.setText("Individual");
        solo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soloActionPerformed(evt);
            }
        });

        grupo.setForeground(new java.awt.Color(255, 255, 255));
        grupo.setText("Grupo");
        grupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grupoActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("$1.00");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Entrada general:");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Monto:");

        txtmonto.setEnabled(false);

        javax.swing.GroupLayout pfLayout = new javax.swing.GroupLayout(pf);
        pf.setLayout(pfLayout);
        pfLayout.setHorizontalGroup(
            pfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pfLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(btnconsul3)
                .addGap(39, 39, 39)
                .addComponent(btnLimpiar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pfLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(pfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pfLayout.createSequentialGroup()
                        .addGroup(pfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pfLayout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(pfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pfLayout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pfLayout.createSequentialGroup()
                                        .addGroup(pfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(grupo)
                                            .addComponent(jLabel3))
                                        .addGap(24, 24, 24)
                                        .addComponent(solo))))
                            .addGroup(pfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(pfLayout.createSequentialGroup()
                                    .addGap(19, 19, 19)
                                    .addGroup(pfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(pfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(pfLayout.createSequentialGroup()
                                                .addComponent(jLabel5)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(txtCan, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(pfLayout.createSequentialGroup()
                                                .addComponent(jLabel6)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtCan1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(pfLayout.createSequentialGroup()
                                            .addGroup(pfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel2)
                                                .addComponent(jLabel4))
                                            .addGap(52, 52, 52)
                                            .addGroup(pfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(txtfecha, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                                                .addComponent(txtmonto)))))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pfLayout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtCan2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(pfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pfLayout.createSequentialGroup()
                                .addGroup(pfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pfLayout.createSequentialGroup()
                                        .addGap(44, 44, 44)
                                        .addGroup(pfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(btnagregar)
                                            .addComponent(btnmodi)
                                            .addComponent(jButton1)))
                                    .addGroup(pfLayout.createSequentialGroup()
                                        .addGap(25, 25, 25)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(45, 45, 45))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pfLayout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(72, 72, 72))))))
        );
        pfLayout.setVerticalGroup(
            pfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pfLayout.createSequentialGroup()
                .addGroup(pfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pfLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnagregar)
                        .addGap(18, 18, 18)
                        .addComponent(btnmodi)
                        .addGap(69, 69, 69)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pfLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(pfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(grupo)
                            .addComponent(solo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(pfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCan1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCan2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(pfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtfecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(pfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pfLayout.createSequentialGroup()
                        .addGroup(pfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtmonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnconsul3)
                    .addComponent(btnLimpiar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pf, javax.swing.GroupLayout.PREFERRED_SIZE, 452, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnconsul3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconsul3ActionPerformed
        MtoVis obj = new MtoVis();
        obj.setModelo((DefaultTableModel)tb.getModel());

        if(obj.consultarTabla())
        {
            tb.setModel(obj.getModelo());

        }
    }//GEN-LAST:event_btnconsul3ActionPerformed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
        MtoVis obj = new MtoVis();
        obj.setId(Integer.parseInt(txtid.getText()));
        int eliminar = JOptionPane.showConfirmDialog(this,  "¿Esta seguro de querer eliminar el registro?", "Atencion", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (eliminar == 0)
        {
            if (obj.Eliminar())
            {
                JOptionPane.showMessageDialog(this, "Datos eliminados");
                limpiar();
                cargarCodigo();

            }

        }
    }//GEN-LAST:event_btneliminarActionPerformed

    private void btnmodiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodiActionPerformed
//        Lista item = (Lista)cbtipo.getSelectedItem();
//        int visita = Integer.parseInt(item.getValue().toString());
        MtoVis obj = new MtoVis();
        obj.setId(Integer.parseInt(txtid.getText()));
        obj.setMonto(Double.parseDouble(txtmonto.getText()));
        obj.setFecha(txtfecha.getText());
      

        if(obj.Modificar())
        {
            JOptionPane.showMessageDialog(this, "Datos Modificados");
            limpiar();
            cargarCodigo();

        }
        else
        {
            JOptionPane.showMessageDialog(this, "ERROR");
        }
    }//GEN-LAST:event_btnmodiActionPerformed

    private void btnagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagregarActionPerformed
//        Lista item = (Lista)cbtipo.getSelectedItem();
//        int visita = Integer.parseInt(item.getValue().toString());
        int suma=0;
        int correcto=1;
        if(txtCan.getText().length()>0){
            suma++;
        }
        if(txtCan1.getText().length()>0){
            suma++;
        }
        if(txtCan2.getText().length()>0){
            suma++;
        }
        
        String msj ="";
        //JOptionPane.showMessageDialog(this,"suma: "+suma+" tipo:"+tipoVisita);
        if(tipoVisita==1 && suma>=2){
            //correcto=1;
        }else{
            msj="Selecciono grupo, por favor completar al menos 2 campos";
            correcto=0;
        }
        if((tipoVisita==2 && suma==1) || correcto==1){
        }else{
            correcto=0;
            msj="Selecciono individual, por favor complete solo 1 campo.";
        }
        if(correcto>0){
            //ingresar en grupo
            MtoGrupo ob = new MtoGrupo();
            ob.setNinos(Integer.parseInt(txtCan.getText()));
            ob.setAdultos(Integer.parseInt(txtCan1.getText()));
            ob.setAncianos(Integer.parseInt(txtCan2.getText()));
            if(ob.guadarGrupo()){
                if(txtCan.getText().length()>0){ // se debe registrar niños
                    MtoVis obj = new MtoVis();
                    obj.setMonto(Integer.parseInt(txtCan.getText())*1);
                    obj.setCodigo(1); // tipo de visita
                    obj.setCantidad(Integer.parseInt(txtCan.getText()));
                    obj.setVisita(visita);
                    obj.setFecha(txtfecha.getText());

                    if(obj.guadar())
                    {
                        JOptionPane.showMessageDialog(this,"Datos Guardados con exito");
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(this, "ERROR");
                    }
                }
                if(txtCan1.getText().length()>0){ // se debe registrar adultos
                    MtoVis obj = new MtoVis();
                    obj.setMonto(Integer.parseInt(txtCan1.getText())*1);
                    obj.setCodigo(2); // tipo de visita
                    obj.setCantidad(Integer.parseInt(txtCan1.getText()));
                    obj.setVisita(visita);
                    obj.setFecha(txtfecha.getText());

                    if(obj.guadar())
                    {
                        JOptionPane.showMessageDialog(this,"Datos Guardados con exito");
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(this, "ERROR");
                    }
                }
                if(txtCan2.getText().length()>0){ // se debe registrar ancianos
                    MtoVis obj = new MtoVis();
                    obj.setMonto(Integer.parseInt(txtCan2.getText())*1);
                    obj.setCodigo(3); // tipo de visita
                    obj.setCantidad(Integer.parseInt(txtCan2.getText()));
                    obj.setVisita(visita);
                    obj.setFecha(txtfecha.getText());

                    if(obj.guadar())
                    {
                        JOptionPane.showMessageDialog(this,"Datos Guardados con exito");
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(this, "ERROR");
                    }
                }
                        cargarCodigo();
                        limpiar();
            }
        }else{
            JOptionPane.showMessageDialog(null, msj);
        }
    }//GEN-LAST:event_btnagregarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:

        limpiar();
        cargarCodigo();

        btnagregar.setEnabled(true);

        btnmodi.setEnabled(false);
        btneliminar.setEnabled(false);

        DefaultTableModel model = (DefaultTableModel)tb.getModel() ;
        model.setRowCount(0) ;
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void tbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbMouseClicked
        // TODO add your handling code here:
           int fila = tb.getSelectedRow();
          
          limpiar();
          btnagregar.setEnabled(false);
          btnmodi.setEnabled(true);
          btneliminar.setEnabled(true);
          //Datos

          
        this.txtid.setText(tb.getValueAt(fila, 0).toString());  
         this.txtmonto.setText(tb.getValueAt(fila, 1).toString()); 
        String fecha = (String) tb.getValueAt(fila,3);
   

       
        txtfecha.setText(fecha);
        
        
    }//GEN-LAST:event_tbMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
             this.dispose(); 
        
        
             FrmVis2 obj = new FrmVis2();
             obj.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtCanKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCanKeyReleased
        calcularMonto();
    }//GEN-LAST:event_txtCanKeyReleased

    private void txtCan1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCan1KeyReleased
        calcularMonto();
    }//GEN-LAST:event_txtCan1KeyReleased

    private void txtCan2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCan2KeyReleased
        calcularMonto();
    }//GEN-LAST:event_txtCan2KeyReleased

    private void grupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grupoActionPerformed
        tipoVisita=1;
       solo.setSelected(false);
    }//GEN-LAST:event_grupoActionPerformed

    private void soloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soloActionPerformed
        tipoVisita=2;
        grupo.setSelected(false);
    }//GEN-LAST:event_soloActionPerformed

    private void calcularMonto(){
    double ninos =0;
        double adu =0;
        double anc =0;
        double ni=0.25;
        double anci=0.50;
       
        
        try{
            ninos = Integer.parseInt((txtCan).getText());
        }catch(Exception e){}
        try{
            adu = Integer.parseInt(txtCan1.getText());
        }catch(Exception e){}
        try{
            anc = Integer.parseInt(txtCan2.getText());
        }catch(Exception e){}
        
      
        double desc = (ninos)*ni;
        double desc1 = (adu)*1;
        double desc2 = (anc)*anci;
        
        double precio1 = ninos - desc;
        double precio2 = anc - desc2;
        
        double tot = precio1 + adu + precio2;
        
        txtmonto.setText(String.valueOf(tot));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmVis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmVis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmVis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmVis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmVis().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnagregar;
    private javax.swing.JButton btnconsul3;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btnmodi;
    private javax.swing.JRadioButton grupo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JPanel pf;
    private javax.swing.JRadioButton solo;
    private javax.swing.JTable tb;
    private javax.swing.JTextField txtCan;
    private javax.swing.JTextField txtCan1;
    private javax.swing.JTextField txtCan2;
    private javax.swing.JTextField txtfecha;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtmonto;
    // End of variables declaration//GEN-END:variables
}
